### ISSUE TITLE
Feature request: Change type of parse violations to errors

### ISSUE THREAD

**Issue by efung** [anboralabs/sqlfluff-intellij-community#11]
The built-in SQL inspections distinguish between linting warnings and parsing errors:

![Screenshot 2023-01-31 at 22 34 13](https://user-images.githubusercontent.com/301094/215938906-c3a00578-4e7c-463a-a499-a7cd9ee59323.png)

It would be nice for sqlfluff linting and parsing output to be rendered similarly.

**Comment by dalgarins** [comment]
it's possible to add this feature but only will work for ultimate version.

**Comment by dalgarins** [comment]
added feature on version: 1.3.0

<img width="1253" alt="Captura de Pantalla 2023-02-08 a la(s) 12 06 16 a m" src="https://user-images.githubusercontent.com/8527174/217439306-1d1ee602-d62c-4986-a809-5618ac387823.png">
