### ISSUE TITLE
IntelliJ 2023.1 and Jinja-based SQL templates not being inspected any more

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [anboralabs/sqlfluff-intellij-community#25]
Unfortunately, it looks like IntelliJ IDEA 2023.1 broke Jinja-templated SQL files pretty hard: it now parses them as HTML!!!

I created a YouTrack issue for this, which has more details: https://youtrack.jetbrains.com/issue/PY-60153/Regression-Jinja-SQL-templates-are-now-analyzed-as-HTML-it-broke-3rd-party-SQLFluff-plugin

In short, it looks like the comparison [isSqlFileType](https://github.com/anboralabs/sqlfluff-intellij-community/blob/c13f0e94594cf618d086dec51b82f23714003833/src/main/kotlin/co/anbora/labs/sqlfluff/lint/LanguageType.kt) function no longer returns true when the file is Jinja templated.  I am observing that the PsiFile.fileType.name now returns `Jinja2` instead.

I am not sure what the correct way a plugin should inspect for a Jinja-templated SQL file, so I asked how to do it on that issue.  Although for the short term it will probably say it's HTML!

As a short-term hack, I am wondering if the plugin should also inspect files when PsiFile.fileType.name is `Jinja2`, and the file extension is `.sql`?

**Comment by dalgarins** [comment]
thank you, I'll be following the steps in the intellij ticket to recreate the issue and try to fix as soon as possible.

**Comment by dalgarins** [comment]
which version of Intellij do you use, community version or ultimate version? because the reason why there are two plugins is also related with how those versions recognise the files in community you don't have a psi for sql files but in ultimate you have the psi to validate files.

**Comment by james-johnston-thumbtack** [comment]
Ultimate:

```
IntelliJ IDEA 2023.1 (Ultimate Edition)

Build #IU-231.8109.175, built on March 28, 2023

Runtime version: 17.0.6+10-b829.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

Worth noting: Jinja support also requires a paid JetBrains product.

**Comment by dalgarins** [comment]
@james-johnston-thumbtack for now it is not possible to fix this issue, you wont have the issue in the plugin version ultimate edition.

try if you want: https://plugins.jetbrains.com/plugin/20534-sqlfluff-linter-ultimate-edition-

**Comment by dalgarins** [comment]
@james-johnston-thumbtack now community version can select the whole word with issue, please update to latest version, also remember to use sqlfluff >= 3.0.0

**Comment by dalgarins** [comment]
@james-johnston-thumbtack could you help me validating this issue?

**Comment by dalgarins** [comment]
fixed issue.
