### ISSUE TITLE
Linter is not raising problems appropriately

### ISSUE THREAD

**Issue by chase-jones** [anboralabs/sqlfluff-intellij-community#40]
Installed SQLFluff Linter Ultimate Edition, but not raising issues.

### Current config screenshots:
<img width="615" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/60072797/e76e72ba-2ad7-4b58-b3c7-745c7e3d84a8">

<img width="678" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/60072797/07339654-6e12-4772-b79c-1771440a7c36">

<img width="956" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/60072797/6e299b43-0112-4288-9919-4664d3ca9bd9">

<img width="783" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/60072797/5d8d88ab-2061-4579-ae68-d10ff4a3ef0c">

#### .sqlfluff file
```
[sqlfluff]
dialect = bigquery
templater = jinja
runaway_limit = 10
max_line_length = 200
indent_unit = space
sql_file_exts = .sql
```

**Comment by chase-jones** [comment]
Version: SQLFluff 2023.5.1

**Comment by dalgarins** [comment]
@chase-jones could you share your sql file?

**Comment by chase-jones** [comment]
<img width="755" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/60072797/cd41d275-dcea-4f6c-b017-d207038d1cef">

**Comment by dalgarins** [comment]
<img width="1398" alt="Screenshot 2023-08-29 at 7 25 59 PM" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/8527174/9dfb6344-c861-4e5e-a427-8c4f49e561b1">

@chase-jones please update to 2023.5.2

**Comment by dalgarins** [comment]
you don't need to change dialect if you are using **.sqlfluff** file

**Comment by chase-jones** [comment]
Hi @dalgarins , I've updated to 2023.5.2, and I'm still running into the issue. I've gotten rid of the dialect flags as well.

<img width="1830" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/60072797/85096bd0-69a0-4ee1-84ab-8ac907ab59a5">

**Comment by dalgarins** [comment]
In my test I used global sqlfluff, I going to double check. thanks for your feedback @chase-jones

**Comment by chase-jones** [comment]
Thank you!

**Comment by dalgarins** [comment]
@chase-jones the new version 2023.5.3, will fix your issue, let me know if you have any other issue.

**Comment by dalgarins** [comment]
@chase-jones the new version 2023.5.3, will fix your issue, let me know if you have any other issue.

**Comment by dalgarins** [comment]
@chase-jones was the issue fixed to you?

**Comment by chase-jones** [comment]
Hi @dalgarins , after updating the linter to 2023.5.3, this issue is still replicated as described above in the 2023.5.2 update. So not resolved yet.

**Comment by chase-jones** [comment]
Hi @dalgarins , any update on this?

**Comment by dalgarins** [comment]
@chase-jones working on it, next week I'm going to continue trying to fix that, I did what you said, clone the repo and install the dependencies form requirements but pip show me an error about dependency versions.

**Comment by dalgarins** [comment]
@chase-jones please update to latest plugin version, let me know if your issue was fixed.

**Comment by chase-jones** [comment]
Hi @dalgarins , this is resolved. Closing
