### ISSUE TITLE
Improve handling of linting warnings/errors

### ISSUE THREAD

**Issue by dhealio** [anboralabs/sqlfluff-intellij-community#50]
# Repro Steps

* Open `.sqlfluff` and set `large_file_skip_byte_limit` to a relatively small value, such as 100.
* Open any SQL file in the project that exceeds the configured value.
* Make changes to the SQL file in the editor and observe.

# Actual Behavior

* Each time the contents of the editor are changed, a warning is shown, e.g. `WARNING Length of file '/project/__sqlfluff_tmp_4598361549568983183.sql' is 500 bytes which is over the limit of 100 bytes. Skipping to avoid parser lock. Users can increase this limit in their config by setting the 'large_file_skip_byte_limit' value, or disable by setting it to zero.`
* Each time the contents of the editor are changed, a new temp file is created.
* None of the temp files mentioned are deleted, which can lead to a lot of garbage over time.

# Expected Behavior

* In general, if a linting warning/error is displayed, it should indicate the name of the file being changed in the editor rather than the name of a temp file.
* In general, any temp files used in the linting process should always be deleted when linting completes, regardless of any warning/error condition encountered.
* In general, duplicate warning/errors should be hidden or throttled in some way.

**Comment by dalgarins** [comment]
@dhealio please update to latest plugin versión, let me know if the issue is fixed.
