### ISSUE TITLE
Rightclick "run sqlfluff fix" Feature Doesn't Work in DataSpell

### ISSUE THREAD

**Issue by coldborecapital** [anboralabs/sqlfluff-intellij-community#51]
Tested in both 2023.3.3 and EAP 2024.1. The right-click menu simply does not include this feature. 
<img width="544" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/59452113/25a8b7a4-0c92-482d-a590-8809e09733fd">

Running version 2023.8.1
<img width="681" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/59452113/bce9a483-e52a-40f8-b789-f78ce3e57153">

**Comment by dalgarins** [comment]
@coldborecapital please right click on the file in the project side, not in the content, could you test it if that fix your issue? also I'll be working to add it from editor.

**Comment by coldborecapital** [comment]
No, doesn't seem to show there either. Maybe it's because the project templater is DBT? 

```
templater = dbt

[sqlfluff:templater:dbt]
project_dir = transform/
```

<img width="378" alt="image" src="https://github.com/anboralabs/sqlfluff-intellij-community/assets/59452113/41f52278-5b3e-4b63-8621-f579f1538c1d">

**Comment by dalgarins** [comment]
ok let's try with some first step, update plugin version to: 2024.3.1

also share with me more details about your IDE, are you using pycharm, rust-rover? which and version, to recreate the issue from my side.

**Comment by jmskarda** [comment]
This also isn't working for me.

- DataGrip 2023.3.4
- Plugin version 2024.3.1
- OS: Windows 11

The community version of the plugin was already installed (and disabled) when I installed the ultimate version today. As a troubleshooting step, I uninstalled both versions of the plugin and installed the ultimate edition only. No change.

That said, this issue doesn't really bother me. I was able to assign a shortcut key to the plugin's format command, which is more efficient than using the context menu anyways.

**Comment by coldborecapital** [comment]
Sorry, I gave up on using the plugin. I thought I would give it a try again, but I'm running into more issues. To follow up on this question though, I'm using DataSpell. I'm going to open another ticket for the other issues.

**Comment by dalgarins** [comment]
@coldborecapital sorry for delay I have been fixing other issues related the temp files, so I decided to rewrite the plugin, I'll let you know when the issue will be fixed.

**Comment by dalgarins** [comment]
@coldborecapital the new version was released could you update and test if your issue was fixed?

**Comment by dalgarins** [comment]
@coldborecapital was the issue fixed to you?

**Comment by dalgarins** [comment]
@coldborecapital could you test this issue with latest plugin version?

**Comment by dalgarins** [comment]
Issue fixed.

**Comment by dalgarins** [comment]
@stevemenke when you open the editor and right click on the content it doesn't show the option? Neither if you right click the file in project view?

Could you add a gift with your steps to reproduce the issue? I would like to validate.
