### ISSUE TITLE
Plugin specifies `--dialect ansi` argument even when removed from its `Arguments (fix):` setting

### ISSUE THREAD

**Issue by jmskarda** [anboralabs/sqlfluff-intellij-community#53]
The `Arguments (fix):` setting in the plugin has a default value of `--dialect ansi`. I would expect that clearing that setting would cause the plugin to call sqlfluff without specifying any dialect argument. However, the plugin still executes the CLI with a `--dialect ansi` argument when the `Arguments (fix):` setting is blank.

I want the plugin to use the same dialect that is configured in my `.sqlfluff` file. I don't want to have to hardcode a global dialect in the plugin. That can be accomplished merely by not overriding that setting with a CLI argument.

A workaround is to specify something in the `Arguments (fix):` setting so that the field isn't entirely blank. For example, when that field is set to `--show-lint-violations` the plugin calls the CLI without the `--dialect ansi` argument.

**Comment by dalgarins** [comment]
@jmskarda please update to latest plugin versión, now the plugin support .sqlfluff config files

**Comment by dalgarins** [comment]
@jmskarda any updates?

**Comment by dalgarins** [comment]
Plugin run configuration change to use .sqlfluff config file. issue fixed on version: 1.6.2

**Comment by jmskarda** [comment]
This seems to be fixed. Thanks!
