### ISSUE TITLE
Getting error of "Requires plugin co.anbora.labs.sqlfluff to be installed" for UE

### ISSUE THREAD

**Issue by chase-jones** [anboralabs/sqlfluff-intellij-community#65]
After updating my pycharm, this plugin is throwing this error:
<img width="413" alt="image" src="https://github.com/user-attachments/assets/6fa1396c-29cd-4c33-ba74-e1673bfb5a50">

Pycharm version info:

```
PyCharm 2024.1.4 (Professional Edition)
Build #PY-241.18034.82, built on June 24, 2024
Licensed to Chase
Subscription is active until January 3, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.intellij.grazie.pro (0.3.324)
  com.intellij.bigdatatools.core (241.18034.62)
  com.intellij.bigdatatools.binary.files (241.14494.158)
  com.intellij.bigdatatools.rfs (241.18034.62)
```

**Comment by dalgarins** [comment]
@chase-jones could you try reinstalling the plugin? That is a weird issue, but it's true that both plugins works together now, because they were sharing common code, or even easier could you install sqlfluff community, and have both installed community and ultimate version.

**Comment by chase-jones** [comment]
Reinstalling worked. Closing
