### ISSUE TITLE
Cannot find binary

### ISSUE THREAD

**Issue by ddbtrmatic** [anboralabs/sqlfluff-intellij-community#67]
Trying to set this plugin up in datagrip and it cannot seem to resolve the sqlfluff binary. I thought it may have been an issue with symlinks but even copying the binary to a new location doesn't work.

![image](https://github.com/user-attachments/assets/b29ed43d-0ce0-4c1a-b588-a16844d1ef98)

![image](https://github.com/user-attachments/assets/fbcca641-759d-4168-a044-8af7709bf6b0)

**Comment by dalgarins** [comment]
@ddbtrmatic could you try adding the sqlfluff yo your path variable? And try to setup again the plugin.

**Comment by ddbtrmatic** [comment]
The following is already part of my USER environment path, which contains sqlfluff.

`C:\Users\<user>\scoop\apps\python\current\Scripts`

**Comment by dalgarins** [comment]
@ddbtrmatic Issue is fixed on version: 1.6.4 please wait until jetbrains approval and let me know if that fix your issue.

**Comment by ddbtrmatic** [comment]
Hey thanks! I'll check it out next week.
