### ISSUE TITLE
Right click menu doesn't work

### ISSUE THREAD

**Issue by Pooort** [anboralabs/sqlfluff-intellij-community#70]
Right click menu doesn't work for me.
PyCharm Version: 2024.2.1
SQLFluff Linter (Ultimate Edition) version: 2024.3.3

![sqlfluff](https://github.com/user-attachments/assets/5ed28a75-fb22-4b37-b4c9-4c2a6d545aec)

**Comment by dalgarins** [comment]
working on it, I have found the issue

**Comment by dalgarins** [comment]
@Pooort new version is available: 2024.3.4, please update your plugin and let me know if the issue is fixed to you.

**Comment by Pooort** [comment]
@dalgarins sorry, still the same:
![image](https://github.com/user-attachments/assets/ddcef8ff-9af5-448d-98c7-8352456c2462)

**Comment by dalgarins** [comment]
@Pooort could you share the sqlfluff settings in your IDE?

**Comment by Pooort** [comment]
This one?
![image](https://github.com/user-attachments/assets/a7caca9b-d3d4-45c4-87cc-d835bd1dfa7e)

**Comment by Pooort** [comment]
@dalgarins any info?

**Comment by dalgarins** [comment]
@Pooort I need a favor, go to settings plugins installed and you will have two plugins of sqlfluff, community and ultimate edition, could you validate if both are updated with last version?

**Comment by Pooort** [comment]
@dalgarins 
![image](https://github.com/user-attachments/assets/460267aa-48f6-4235-a3a2-b92089865601)

**Comment by dalgarins** [comment]
@Pooort I have created a new release to always show the option `run sqlfluff lint`, the version will be 2024.3.5, let me know if that fix your issue, please wait until jetbrains approval to see the update.

**Comment by dalgarins** [comment]
@Pooort please update the plugin and let me know if the issue is fixed to you.

**Comment by Pooort** [comment]
@dalgarins the same state:

![image](https://github.com/user-attachments/assets/09ace60d-ca3b-4837-aa77-130c861c073e)

![image](https://github.com/user-attachments/assets/9fd2c772-de85-4da6-b32a-52707b0d1a90)

![image](https://github.com/user-attachments/assets/a2bdc2a6-4562-4999-b56e-f7cffe72e55d)

**Comment by Pooort** [comment]
Hi, @dalgarins. Any info?

**Comment by dalgarins** [comment]
@Pooort please do the following steps, uninstall both sqlfluff plugins restart the ide, and install again sqlfluff ultimate edition, also open your test.sql and move your mouse over a highlighted error it will show you a quick fix popup, validate if you see also that pop-up.

**Comment by Pooort** [comment]
@dalgarins yes, I see fix popup like this:
![image](https://github.com/user-attachments/assets/ae673780-0c61-43bf-a267-2e81a6ba88a7)

But:
1. Nothing happen when I click to 'Change to upper case'
2. No right click menu item like in description:
![image](https://github.com/user-attachments/assets/19267fbb-5dc3-4297-b239-93c3231f4ecd)

**Comment by dalgarins** [comment]
@Pooort please schedule a meet: [https://calendly.com/dalgarins](https://calendly.com/dalgarins) I really want to understand your issue and fix it.

**Comment by dalgarins** [comment]
@Pooort please update to latest version and let me know if the right click option on editor is available, also please support my work giving me some starts on intellij marketplace.

**Comment by dalgarins** [comment]
@Pooort only clicking on the popup fix option for some violations, right it's not possible to fix selected text, but create a new issue, I will work on that.
