### ISSUE TITLE
Show parse errors when linting

### ISSUE THREAD

**Issue by efung** [anboralabs/sqlfluff-intellij-community#8]
I'm using the Community plugin version 1.2.1, with sqlfluff version 1.4.5 on macOS 13.2.

When sqlfluff is linting an SQL file, it shows all of the lint warnings. But parse errors are not surfaced. 

Can this be added?

Here's an example:

```sql
SELECT "Shop ID"
FOM my_table
```

From the CLI:

```bash
$ sqlfluff lint --dialect postgres blah.sql
== [blah.sql] FAIL
L:   1 | P:   8 | L057 | Do not use special characters in identifiers.
L:   2 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 01]
L:   2 | P:   1 | L012 | Implicit/explicit aliasing of columns.
L:   2 | P:   5 |  PRS | Line 2, Position 5: Found unparsable section: 'my_table'
```

Note the `PRS` parse error that it reports.

But from IntelliJ:
<img width="574" alt="Screenshot 2023-01-31 at 17 59 02" src="https://user-images.githubusercontent.com/301094/215903232-4496af13-c686-4f95-9309-2d6a4144a2dc.png">

**Comment by dalgarins** [comment]
Hi @efung, did you change the dialect in the linter configuration to postgres? I mean: instead of ansi change to postgres?.

![linter](https://user-images.githubusercontent.com/8527174/215905650-e0585e03-5855-456b-b38e-f410f1acd406.jpg)

**Comment by dalgarins** [comment]
@efung forget about the last comment, yes, there is an issue, I going to fix it. thanks a lot.

**Comment by dalgarins** [comment]
@efung the fix will be available on version: 1.2.2

<img width="910" alt="Captura de Pantalla 2023-01-31 a la(s) 8 39 06 p m" src="https://user-images.githubusercontent.com/8527174/215923973-77891cec-4949-401b-be36-99e0a867dab5.png">

**Comment by efung** [comment]
Wow, thanks for looking at this so quickly.

Instead of treating parse failures as a warning, what do you think about making them errors?

**Comment by dalgarins** [comment]
I think that it is a good idea, I'm going to implement that but please create another issue and will mark that issue as a feature request. I will close this issue when you test the recent changes on the new plugin version.

**Comment by efung** [comment]
I just installed plugin version 1.2.3 and can verify that this version displays parse errors.

<img width="572" alt="Screenshot 2023-02-02 at 09 46 04" src="https://user-images.githubusercontent.com/301094/216356276-ec2ccdd9-8652-477f-93d6-fa0a1f7e6442.png">
